### ISSUE TITLE
Firesize no longer up.

### ISSUE THREAD

**Issue by tewen** [curiositry/mnml-ghost-theme#31]
It appears that firesize.com is no longer up and resizing images. You can see this on the sample page for mnml: [here](http://mnml.herokuapp.com/). I first noticed on my mnml blog [pearoftheweek.com](http://www.pearoftheweek.com). Thanks

**Comment by vickychijwani** [comment]
Same issue here. I ended up getting rid of the firesize and using a pure CSS solution for center-cropping, described here (the 2nd one): http://stackoverflow.com/a/11552460/504611. Note that the you need to add `background-size: cover;` to the `.center-cropped` CSS for it to work correctly. Which means:

```handlebars
// partials/loop.hbs
function homepagePostThumbnail (imgUrl) {
    thumbnailContainer.innerHTML = '<div class="center-crop" style="background-image: url(\'' + imgUrl + '\')">'
        + '<img src="'+imgUrl+'" height="150" alt="{{title}}" /></div>';
}
```

```css
// assets/css/main.css
.post-thumbnail .center-crop {                                                                                                                       
  max-width: 250px;                                                                                                                                  
  height: 150px;                                                                                                                                     
  background-position: center center;                                                                                                                
  background-repeat: no-repeat;                                                                                                                      
  background-size: cover;                                                                                                                            
  overflow: hidden;                                                                                                                                  
}                                                                                                                                                    
                                                                                                                                                     
/* Set the image to fill its parent and make transparent */                                                                                          
.post-thumbnail .center-crop img {                                                                                                                   
  min-height: 100%;                                                                                                                                  
  min-width: 100%;                                                                                                                                   
  /* IE 8 */                                                                                                                                         
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";                                                                                  
  /* IE 5-7 */                                                                                                                                       
  filter: alpha(opacity=0);                                                                                                                          
  /* modern browsers */                                                                                                                              
  opacity: 0;                                                                                                                                        
}                                                                                                                                                    
```

This workaround is obviously trading-off some bandwidth and page load speed but I can live with that.
